{% set name = "dpcmaps" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6b62debfbf3e3e841d2d9455fa096c8de3612e61ad46c69e0fa6b8974498298

build:
  number: 0
  noarch: python
  entry_points:
    - dpcmaps = dpcmaps.dpc_gui:run_dpc_gui
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - h5py
    - matplotlib-base
    - numpy
    - pillow
    - psutil
    - pyqt
    - scikit-image
    - tifffile

test:
  imports:
    - dpcmaps
    - dpcmaps.db_config
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NSLS-II/dpcmaps
  summary: Software for Diffraction Phase Correlation (DPC) analysis
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: http://nsls-ii.github.io/dpcmaps
  dev_url: https://github.com/NSLS-II/dpcmaps

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
