{% set name = "dpcmaps" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3eabf6b82ba40c04a6c6096a5b69860850a21b8ea5d3cae6d8ce35b58efd6905

build:
  number: 0
  noarch: python
  entry_points:
    - dpcmaps = dpcmaps.dpc_gui:run_dpc_gui
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - h5py
    - matplotlib-base
    - numpy
    - pillow
    - psutil
    - pyqt
    - scikit-image
    - tifffile

test:
  imports:
    - dpcmaps
    - dpcmaps.db_config
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NSLS-II/dpcmaps
  summary: Software for Diffraction Phase Correlation (DPC) analysis
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: http://nsls-ii.github.io/dpcmaps
  dev_url: https://github.com/NSLS-II/dpcmaps

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
