{% set name = "dpcmaps" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dpcmaps-{{ version }}.tar.gz
  sha256: 721b0b3fa8543b58d6002859e19210fa3fc9aa15f234926846c7ad7297fe5b7c

build:
  number: 0
  noarch: python
  entry_points:
    - dpcmaps = dpcmaps.dpc_gui:run_dpc_gui
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - h5py
    - matplotlib-base
    - numpy
    - pillow
    - psutil
    - python >=3.7
    - pyqt
    - scikit-image
    - tifffile

test:
  imports:
    - dpcmaps
    - dpcmaps.db_config
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com//NSLS-II//dpcmaps
  summary: Software for generating and analysis of DPC Maps
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
